from enum import Enum


class ErrorTypeEnum(Enum):
    DUPLICATE_FIELD_ERROR = 'DUPLICATE_FIELD_ERROR'
    EMPTY_DATA_ERROR = 'EMPTY_DATA_ERROR'
    INTERNAL_ERROR = 'INTERNAL_ERROR'
    UNKNOWN_ERROR = 'UNKNOWN_ERROR'
