from enum import Enum


class ErrorTypeEnum(Enum):
    UNAUTHORIZED_ERROR = 'UNAUTHORIZED_ERROR'
    INVALID_CREDENTIALS_ERROR = 'INVALID_CREDENTIALS_ERROR'
    DUPLICATE_FIELD_ERROR = 'DUPLICATE_FIELD_ERROR'
    EMPTY_DATA_ERROR = 'EMPTY_DATA_ERROR'
    INTERNAL_ERROR = 'INTERNAL_ERROR'
    UNKNOWN_ERROR = 'UNKNOWN_ERROR'
