from enum import Enum


ENDPOINT_NAME = '/graphql'


class ErrorTypeEnum(Enum):
    INVALID_CREDENTIALS_ERROR = 'INVALID_CREDENTIALS_ERROR'
    DUPLICATE_FIELD_ERROR = 'DUPLICATE_FIELD_ERROR'
    EMPTY_DATA_ERROR = 'EMPTY_DATA_ERROR'
    UNKNOWN_ERROR = 'UNKNOWN_ERROR'
    INTERNAL_ERROR = 'INTERNAL_ERROR'
